"""Modificación de las tablas de pedido y pagos

Revision ID: 09b00a42f666
Revises: fb003f64aee8
Create Date: 2025-01-30 18:14:50.429749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b00a42f666'
down_revision: Union[str, None] = 'fb003f64aee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('extras', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('exclusions', sa.String(), nullable=True))
    op.drop_column('order_items', 'precio')
    op.drop_column('order_items', 'cantidad')
    op.drop_column('order_items', 'nombre')
    op.add_column('orders', sa.Column('table_number', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'mesa')
    op.add_column('payments', sa.Column('method', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint('payments_redsys_payment_id_key', 'payments', type_='unique')
    op.drop_column('payments', 'redsys_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('redsys_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('payments_redsys_payment_id_key', 'payments', ['redsys_payment_id'])
    op.drop_column('payments', 'amount')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'method')
    op.add_column('orders', sa.Column('mesa', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'table_number')
    op.add_column('order_items', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'exclusions')
    op.drop_column('order_items', 'extras')
    op.drop_column('order_items', 'quantity')
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
