"""Evitar mensajes duplicados

Revision ID: 0d5168897e16
Revises: b536a6240474
Create Date: 2025-01-29 20:52:15.168498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5168897e16'
down_revision: Union[str, None] = 'b536a6240474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_processed_messages_message_id'), 'processed_messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_messages_message_id'), table_name='processed_messages')
    op.drop_table('processed_messages')
    # ### end Alembic commands ###
