"""Agregar campos de personalización en tenants - ingles

Revision ID: 58a08803e08c
Revises: cfd384128a01
Create Date: 2025-01-31 13:58:14.712850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a08803e08c'
down_revision: Union[str, None] = 'cfd384128a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('waiter_name', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('business_name', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('table_number_min', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('table_number_max', sa.Integer(), nullable=True))
    op.drop_column('tenants', 'nombre_local')
    op.drop_column('tenants', 'nombre_camarero')
    op.drop_column('tenants', 'numero_mesa_maximo')
    op.drop_column('tenants', 'numero_mesa_minimo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('numero_mesa_minimo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('numero_mesa_maximo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('nombre_camarero', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('nombre_local', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'table_number_max')
    op.drop_column('tenants', 'table_number_min')
    op.drop_column('tenants', 'business_name')
    op.drop_column('tenants', 'waiter_name')
    # ### end Alembic commands ###
