"""Hacer que el campo Token no sea NULL

Revision ID: 6e16b992d1e7
Revises: a2a6e6135ba3
Create Date: 2025-01-31 14:15:13.399895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e16b992d1e7'
down_revision: Union[str, None] = 'a2a6e6135ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'whatsapp_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'whatsapp_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
