"""Eliminar tabla message_logs

Revision ID: 7b9c9ab3dcaa
Revises: ced19f7288fd
Create Date: 2025-01-29 18:15:48.984492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9c9ab3dcaa'
down_revision: Union[str, None] = 'ced19f7288fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_logs_id', table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_session_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='message_logs_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='message_logs_pkey'),
    sa.UniqueConstraint('message_id', name='message_logs_message_id_key')
    )
    op.create_index('ix_message_logs_id', 'message_logs', ['id'], unique=False)
    # ### end Alembic commands ###
