"""Eliminar restricción única en user_id

Revision ID: 95f888e6fd26
Revises: 58dbe440f4d8
Create Date: 2025-01-29 17:27:50.957815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f888e6fd26'
down_revision: Union[str, None] = '58dbe440f4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_user_id_key', 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sessions_user_id_key', 'sessions', ['user_id'])
    # ### end Alembic commands ###
