"""Agregar customer_phone en la tabla order

Revision ID: 976c22b806f4
Revises: d2c5964170e2
Create Date: 2025-01-30 19:38:35.978054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976c22b806f4'
down_revision: Union[str, None] = 'd2c5964170e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_phone')
    # ### end Alembic commands ###
