"""Agregar token whatsapp unico

Revision ID: a2a6e6135ba3
Revises: 58a08803e08c
Create Date: 2025-01-31 14:13:40.027609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a6e6135ba3'
down_revision: Union[str, None] = '58a08803e08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('whatsapp_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'whatsapp_token')
    # ### end Alembic commands ###
