"""Eliminacion de formato cascada y mantengo los MensajesID para auditar sesiones

Revision ID: ced19f7288fd
Revises: a5eae4702d54
Create Date: 2025-01-29 17:53:32.521502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced19f7288fd'
down_revision: Union[str, None] = 'a5eae4702d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_logs', sa.Column('is_session_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_logs', 'is_session_active')
    # ### end Alembic commands ###
