"""Arreglo de problemas con la zona horaria

Revision ID: d2c5964170e2
Revises: 09b00a42f666
Create Date: 2025-01-30 18:39:34.392673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c5964170e2'
down_revision: Union[str, None] = '09b00a42f666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
